name: english_words_300k
description: A Dart package containing over 300,000 English words with a minimum length of 4 letters.
version: 1.0.0
repository: https://github.com/devsdocs/english_words_300k

environment:
  sdk: ^3.0.6

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
